# project name
spring.application.name=Student Management System

# Database Config
#spring.datasource.url= jdbc:postgresql://dpg-d775vphaae7s73bmj2o0-a:5432/studentdb_i5c4
# external url
spring.datasource.url= jdbc:postgresql://dpg-d775vphaae7s73bmj2o0-a.virginia-postgres.render.com:5432/studentdb_i5c4
spring.datasource.username=studentdb_i5c4_user
spring.datasource.password=EOBfIxeBURe2JLGQ2HWye2GoTPruHWmY



# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql= false
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#path setup
server.servlet.context-path=/manage/api

# Security Disable (temporary)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Debug
logging.level.org.springframework.security=DEBUG