spring.application.name=Student Management System

#database config
spring.datasource.url= jdbc:postgresql://dpg-d775vphaae7s73bmj2o0-a:5432/studentdb_i5c4
spring.datasource.username=studentdb_i5c4_user
spring.datasource.password=EOBfIxeBURe2JLGQ2HWye2GoTPruHWmY

# format and highlight config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql= false
spring.jpa.properties.hibernate.highlight_sql=true

#
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#path setup
server.servlet.context-path=/manage/api

# to exclude the db config 
#spring.autoconfigure.exclude= org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# disable started security for now
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Debug log
logging.level.org.springframework.security=DEBUG